services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8014981050:AAFFPBSf9R3KEQf8fwFF4I0SWidxaxwodFI"  # Replace with your actual bot token
      - key: GROUP_CHAT_ID
        value: "-1002416009587"  # Replace with your group chat ID
      - key: RENDER_EXTERNAL_URL
        sync: true
